---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template installs a MongoDB cluster into an existing VPC.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    VPC:
        Description: 'VCP to install the instances into'
        Type: 'AWS::EC2::VPC::Id'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'AWS::EC2::KeyPair::KeyName'
        Default: 'asgard-lite-test'

    InstanceType:
        Description: 'How large of a box to run your containers on'
        Type: 'String'
        Default: 't2.small'

    VolumeSize:
        Description: 'The size of the volume, in gibibytes (GiBs).'
        Type: 'Number'
        Default: '16'

    VolumeType:
        Description: 'The volume type. Acceptable values are gp2, io1, st1, sc1 and standard'
        Type: 'String'
        Default: 'gp2'

    Subnets:
        Description: 'Which subnets the EC2 instances should be deployed to.'
        Type: List<AWS::EC2::Subnet::Id>

Mappings:
    # these AMIs change regularly.  Check http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
    RegionToAmazonAMI:
        us-east-1:
            HVM64: not-set
        us-east-2:
            HVM64: not-set
        us-west-1:
            HVM64: not-set
        us-west-2:
            HVM64: ami-d6bd34b6

Resources:
    #SSH and MongoDB ports only
    MongoDBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: 'MongoDB Traffic'
            VpcId:
                Ref: 'VPC'
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 27017
                  ToPort: 27019
                  CidrIp: 0.0.0.0/0
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'MongoDB', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'MongoDB traffic only'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    AlphaInstance:
        Type: "AWS::EC2::Instance"
        Properties:
            BlockDeviceMappings:
                - DeviceName: /dev/xvdf
                  Ebs:
                      DeleteOnTermination: true
                      VolumeSize:
                          Ref: VolumeSize
                      VolumeType:
                          Ref: VolumeType
            EbsOptimized: false
            ImageId:
                Fn::FindInMap:
                    - RegionToAmazonAMI
                    - Ref: 'AWS::Region'
                    - HVM64
            InstanceInitiatedShutdownBehavior: 'stop'
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: SshKeyName
            Monitoring: false
            SecurityGroupIds:
                - !Ref MongoDBSecurityGroup
            SourceDestCheck: true
            SubnetId:
                Fn::Select: [ 0, !Ref Subnets ]
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'MongoDB Alpha', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'MongoDB Replica Set'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'Master Node'
            Tenancy: 'default'

    BravoInstance:
        Type: "AWS::EC2::Instance"
        Properties:
            BlockDeviceMappings:
                - DeviceName: /dev/xvdf
                  Ebs:
                      DeleteOnTermination: true
                      VolumeSize:
                          Ref: VolumeSize
                      VolumeType:
                          Ref: VolumeType
            EbsOptimized: false
            ImageId:
                Fn::FindInMap:
                    - RegionToAmazonAMI
                    - Ref: 'AWS::Region'
                    - HVM64
            InstanceInitiatedShutdownBehavior: 'stop'
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: SshKeyName
            Monitoring: false
            SecurityGroupIds:
                - !Ref MongoDBSecurityGroup
            SourceDestCheck: true
            SubnetId:
                Fn::Select: [ 1, !Ref Subnets ]
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'MongoDB Bravo', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'MongoDB Replica Set'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'Master Node'
            Tenancy: 'default'

    CharlieInstance:
        Type: "AWS::EC2::Instance"
        Properties:
            BlockDeviceMappings:
                - DeviceName: /dev/xvdf
                  Ebs:
                      DeleteOnTermination: true
                      VolumeSize:
                          Ref: VolumeSize
                      VolumeType:
                          Ref: VolumeType
            EbsOptimized: false
            ImageId:
                Fn::FindInMap:
                    - RegionToAmazonAMI
                    - Ref: 'AWS::Region'
                    - HVM64
            InstanceInitiatedShutdownBehavior: 'stop'
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: SshKeyName
            Monitoring: false
            SecurityGroupIds:
                - !Ref MongoDBSecurityGroup
            SourceDestCheck: true
            SubnetId:
                Fn::Select: [ 2, !Ref Subnets ]
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'MongoDB Charlie', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'MongoDB Replica Set'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'Master Node'
            Tenancy: 'default'

Outputs:
    AlphaPrivateAddress:
        Description: 'The private IP address of the master instance.'
        Value: !GetAtt AlphaInstance.PrivateIp
    BravoPrivateAddress:
        Description: 'The private IP address of the secondary instance.'
        Value: !GetAtt BravoInstance.PrivateIp
    CharliePrivateAddress:
        Description: 'The private IP address of the tertiary instance.'
        Value: !GetAtt CharlieInstance.PrivateIp
